# Specify services that will interact
services:

  frontend:
    image: cooopeir/conint_frontend:latest

    container_name: frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "5173:5173"

  mariadb:
    image: cooopeir/conint_db:latest

    # build:
    #   context: ./mariadb
    #   dockerfile: Dockerfile

    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: todo-admin
      MYSQL_PASSWORD: admin-pw
      MYSQL_DATABASE: tododot
    
    ports:
      - "3306:3306"
    
    restart: always

    volumes:
      - mariadb_volume_v2:/var/lib/mysql

    networks:
      - backend_mariadb

  backend:
    image: cooopeir/conint:latest

    depends_on:
      - mariadb

    restart: always

    environment:
      - "DB_DIALECT=mariadb"
      - "DB_USER=todo-admin"
      - "DB_PW=admin-pw"
      - "DB_HOST=mariadb"
      - "DB_NAME=tododot"

    env_file: 
      - ./backend/env.local

    ports:
      - "8080:8080"
    
    networks:
      - backend_mariadb

networks:
  backend_mariadb:

volumes:
  mariadb_volume_v2: 