# Specify Version
version: '3.3'

# Specify services that will interact
services:

  frontend:
    image: cooopeir/conint_frontend:latest

    restart: always

    depends_on:
      - backend

    ports:
      - "8080:8080"

  backend:
    image: cooopeir/conint:latest

    restart: always

    # env_file:
    #   - ./backend/env.local

    # environment:
    #   - "DB_DIALECT=mariadb"
    #   - "DB_USER=todo-admin"
    #   - "DB_PW=admin-pw"
    #   - "DB_HOST=mariadb:3306"
    #   - "DB_NAME=tododot"

    ports:
      - "44123:44123"

    volumes:
      - todo_data:/app/data


volumes:
  todo_data:

