# Specify services that will interact
services:

  frontend:
    image: cooopeir/conint_frontend:latest

    container_name: frontend

    restart: on-failure

    depends_on:
      - backend

    ports:
      - "5173:5173"

  mariadb:
    image: mariadb:latest

    container_name: db

    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: todo-admin
      MYSQL_PASSWORD: admin-pw
      MYSQL_DATABASE: tododot
    
    ports:
      - "3306:3306"
    
    restart: on-failure

    volumes:
      - mariadb-data:/var/lib/data

  backend:
    image: cooopeir/conint:latest

    container_name: backend
    # SEE HOW ENVIRONMENT VARIABLES WORK IN this image

    depends_on:
      - mariadb

    restart: on-failure

    # env_file:
    #   - ./backend/env.local

    # environment:
    #   - "DB_DIALECT=mariadb"
    #   - "DB_USER=todo-admin"
    #   - "DB_PW=admin-pw"
    #   - "DB_HOST=mariadb:3306"
    #   - "DB_NAME=tododot"

    ports:
      - "8080:8080"

networks:
  backend:
    driver: bridge

volumes:
  mariadb-data: 